### ISSUE TITLE
Value for quarkus.kubernetes-config.secrets 

### ISSUE THREAD

**Issue by white-collar** [cescoffier/hello-quarkus#1]
Sorry, it's not issue, but question: it's not clear what value is assigned to `quarkus.kubernetes-config.secrets=movies-secret` ?

Thanks

**Comment by cescoffier** [comment]
It's the name of the Kubernetes secret containing the Movie API key:

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: movies-secret
type: Opaque
data:
  api-key: your-key-base64-encoded
```
